### ISSUE TITLE
StringencyIndexForDisplay data missing/NaN for last 2 days for over 100 countries

### ISSUE THREAD

**Issue by KlausGPaul** [OxCGRT/covid-policy-tracker#15]
First of all, thank you very much for the fantastic job you are doing. I am using it for "my" dashboard at https://got-data-for.me/wmap to visualise the global situation (dropdown string_idx).

When updating the data for that dashboard, as my data pipeline is not yet fully up (there is always a little bit that needs fixing) I do encounter frequent missing data points for StringencyIndexForDisplay, often around 30...50 countries, missing yesterday's data. I am usually padding this myself.

Ever since day before yesterday, though, things have changes substantially, it seems. Many countries lack data for two days, there is countries with NaN in StringencyIndexForDisplay, so padding got very challenging recently.

It appears as if something has changed and data quality is affected, unfortunately I cannot point you to the source of it. The data from 2020-06-01 was the last one I managed to successfully pad.

Keep up your excellent work!

**Comment by TobyPhillips** [comment]
Thanks for flagging this. We seem to have an issue with the way we pull forward data internally. It is fine for days up to 31 May (I think), but breaks after that. We have identified the cause and just figuring out the best way to fix it.

**Comment by TobyPhillips** [comment]
I think we have this fixed now; let me know if you still see an issue.
-Toby

**Comment by KlausGPaul** [comment]
StringencyIndexForDisplay now is padded as intended, issue is closed.
Thanks for your help!
Klaus
