### ISSUE TITLE
Policy Measures in US States don't seem correct

### ISSUE THREAD

**Issue by jsilve24** [OxCGRT/covid-policy-tracker#16]
Thanks for putting this package together!.

Looking at Georgia I notice that all policy variables have increased over time without any decrease. Georgia has relaxed a number of restrictions and this relaxation does not seem to be accounted for.

Could you please shine some light on this?

**Comment by TobyPhillips** [comment]
Hi, thanks for the message.
We don't currently record data for US states – all of our entries are at the national level. Georgia refers to the East European country. We are planning to start collecting state-level data for some countries soon, but it will be some time before this is completed.

**Comment by jsilve24** [comment]
Ahh, its an issue with the COVID19 package which is somehow assigning state-level variables. Still, I would imagine that the US should have decreasing severity with recent reopenings occurring across the country.

**Comment by TobyPhillips** [comment]
Hmm, what is the COVID19 package? Perhaps worth submitting an issue to them.

With national US data, the rollbacks don't actually change much in our database (this is a limitation of our data structure). 
Previously you had some, but not all, states implementing strong lockdown measures – so these were coded as geographically targeted.
Even though several states have rolled these back, there are still some states with these measures in place – so our database continues to reflect that these measures exist in a geographically targeted way. As long as some states still have the measures in place, it is recorded the same whether it is 40 states or 10 states.

This is why we plan to start collecting sub-national data, so we can factor in the extent of the geographical scope.
