### ISSUE TITLE
Data problem for FRA with latest update

### ISSUE THREAD

**Issue by palima** [OxCGRT/covid-policy-tracker#18]
Hi,

It looks like the latest updated pushed broke the data entries for France: the values for the containment health index and the C6 Stay at home requirements are now all the same from Feb, 5th till the latest date available, which wasn't the case previously. The problem seems to apply to other indexes and indicators as well.

data source: [https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv](https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv)

![indexes for FRA](https://user-images.githubusercontent.com/5647714/84008455-347a0800-a972-11ea-8b30-244f51ab9b3e.jpg)

**Comment by TobyPhillips** [comment]
Thanks for flagging this. I believe the error is fixed now, but please let me know if you still see it.

**Comment by palima** [comment]
Yes, fixed! Thanks for the quick fix and your hard work on this important dataset.
