### ISSUE TITLE
Possible to see chart's code ? 

### ISSUE THREAD

**Issue by pixyfox** [OxCGRT/covid-policy-tracker#19]
Hello OxCGRT team,

First of all, thank you for the amazing work you are doing. I'm using your data for some academic research and it has been a great source.

I'm trying to study some correlations and causality. I wondererd if it was possible to see the codes used to make the charts in order to customize them for specific studies.

Thanks !
Leo

**Comment by TobyPhillips** [comment]
Hi Leo, the charts are made in Stata. I don't have the code for all the charts in one place – they are scattered across several .do files, and it will take a while to compile them all (publishing this code in a single file is on my to-do list, but just not at the top).

Is there a specific chart you are interested in? Happy to grab the code for that and share it here. I just don't have the time to go through all of them.

**Comment by pixyfox** [comment]
Hi Toby, thank you for your fast reply. 
I'm interested especially in the chart named «relationship between number of COVID-19 cases and government response».

I will try with Strada and see what I can get. Thank you !

**Comment by TobyPhillips** [comment]
Here is the code to generate that chart in Stata:

```
gen cases_log10=log10(confirmedcases+1)
label define log10label -8 "0.00000001" -7 "0.0000001" -6 "0.000001" -5 "0.00001" -4 "0.0001" -3 "0.001" -2 "0.01" -1 "0.1" 0 "1" 1 "10" 2 "100" 3 "1,000" 4 "10,000" 5 "100,000" 6 "1,000,000"
label values cases_log10 log10label

drop if confirmedcases<1
collapse (max) confirmedcases confirmeddeaths governmentresponseindexfordispla cases_log10 , by(countrycode)
replace countrycode="" if (countrycode!="ITA" & countrycode!="CHN" ///
	& countrycode!="USA" & countrycode!="GBR" & countrycode!="KOR" & countrycode!="SWE" ///
	& countrycode!="SGP" & countrycode!="HKG" & countrycode!="TWN" & countrycode!="PNG" & countrycode!="NIC" ///
	& countrycode!="KEN")
twoway scatter governmentresponseindexfordispla cases_log10, xlabel(0 "1" 1 "10" 2 "100" 3 "1,000" 4 "10,000" 5 "100,000" 6 "1,000,000") mlabel(countrycode) mlabposition(9) ///
	|| lfit governmentresponseindexfordispla cases_log10, xtitle("Number of COVID-19 cases") ytitle("Maximum government response level") title("Relationship between number of COVID-19 cases and government response", span position(11)) legend(off)
```

**Comment by pixyfox** [comment]
Thank you Tobi !
