### ISSUE TITLE
Missing data for Slovenia

### ISSUE THREAD

**Issue by mkadunc** [OxCGRT/covid-policy-tracker#2]
I noticed you have N/A for Slovenia in the "International travel controls" category.

I don't know whether this will help, but the following government site lists several measures in chapter "Measures at borders"

https://www.gov.si/en/topics/coronavirus-disease-covid-19/measures-to-curb-the-spread-of-the-coronavirus/

**Comment by TobyPhillips** [comment]
Hi mkadunc, not every country is perfectly up to date, so there are often empty cells for the most recent days.
Our last recorded measure for international travel controls is actually 3, the highest rating, on 13 April 2020. You can see this here: https://github.com/OxCGRT/covid-policy-tracker/blob/master/data/timeseries/s7_internationaltravel.csv
