### ISSUE TITLE
Current CSV file contents ~12:00 p.m. EST 06/20/2020

### ISSUE THREAD

**Issue by mgudorf** [OxCGRT/covid-policy-tracker#23]
The latest version of the .CSV files (e.g. OxCGRT_latest.csv) does not in fact contain the correct data, but rather, it contains what looks like html code.

**Comment by rcatlord** [comment]
Yes, it looks like this:
<img width="579" alt="OxCGRT_latest" src="https://user-images.githubusercontent.com/12719575/85208314-2f7c6780-b327-11ea-8172-b53983be9dab.png">

**Comment by TobyPhillips** [comment]
Thanks for bringing this to our attention. We moved the database onto a new server this week, so it might be related to that. I have reverted back to a previous csv export and paused the auto-update script while we figure it out. The CSVs on this repo should be good now, but they just won't update with new data until we solve the problem.

**Comment by mgudorf** [comment]
Thanks!
