### ISSUE TITLE
CZE C8_International travel controls value

### ISSUE THREAD

**Issue by Yop127** [OxCGRT/covid-policy-tracker#24]
Hello, 
Value for CZE C8 criteria is 4, ie total travel ban for the last few days. However, there is no total ban for CZE.
According to IATA: https://www.iatatravelcentre.com/international-travel-document-news/1580226297.htm
"Published 16.06.2020
1. Passengers are not allowed to enter.
This does not apply to:
-nationals of Croatia and their family members.
-nationals of Austria, Czechia, Estonia, Germany, Hungary, Latvia, Lithuania, Poland, Slovakia and Slovenia."

**Comment by TobyPhillips** [comment]
Thanks for flagging this, I think it is an error but have asked our data collector for Czech Republic to have a look.
