### ISSUE TITLE
Are there still plans to compiled US state by state index?

### ISSUE THREAD

**Issue by gregbert42** [OxCGRT/covid-policy-tracker#26]
This was mentioned in WSJ in May, but i don't see this level of detail in the date yet. I was wondering if there are still plans to do this or whether it has been deprioritized. Thank you.

**Comment by TobyPhillips** [comment]
Thanks for asking, this is our top priority in terms of future development (although our top overall priority is always to keep our country-level data as up-to-date as possible). We now have people working on all 50 states but to be perfectly honest, it is slow going to build a comprehensive timeline back to January. The "start up" cost of coding a new entity is much higher now (7 months into the year) than it was when we started with countries back in March, so it takes a while to set up new entities.

I hope we will have completed data collection within the next couple of weeks. It may still be a bit of time beyond that for us to do due diligence checks and connect to our broader data architecture + this GitHub repo. Sorry I can't be more precise about the timeline.

**Comment by gregbert42** [comment]
Hi Toby,

Thank you very much. You know, I am actually just looking for the overall
stringency calculation 'now', updated frequently, rather than the
comprehensive timeline going back to January.
It sounds like you may already have that, because that does not include the
'start-up' cost of coding. Right now I am using IHME data, but that is a
much less granular at the policy level.

Would it be conceivable to start giving access to the current US state data
sooner?

Greg

**Comment by TobyPhillips** [comment]
Hi Greg, unfortunately not.

Partly because we are going state-by-state, not starting most recently. So for instance, we don't have 30 July for all states. But the biggest barrier is that data collection is just the first step (very almost completed, anyway), and we are only just now turning our attention to re-coding our data architecture pipelines so that the data recorded in our backend database can be smoothly incorporated into the CSVs posted here. This is a bit of a case of "building the aeroplane as we fly it"

**Comment by gregbert42** [comment]
Yeah, we are all doing that at the moment. I believe that there is emerging
evidence for an 'apparent' herd immunity in US states that have a higher
cumulative covid load, and also have strong policies and/or social
distancing rules in place. Ronny Gal provided some great analysis a few
weeks back as part of Bernstein. I recently put together this animated
graph: www.hersches.com/covid - where you can clearly see FL and AZ
following a different pattern in the US vs. NY,NJ,MA, etc.  Ronny was
telling me that he really wants to be able to measure mask-wearing..

Greg
(none of this represents novartis, my employer)

**Comment by dsargent** [comment]
Hi @TobyPhillips, thanks for the updates! Is there any chance we could get a sneak peek at the per-state data, even if it's just a couple of states (or half a state!) so we can beginning preparing our code to ingest it? Mainly interested in seeing the schema, how it might differ from the per-country data etc.

**Comment by TobyPhillips** [comment]
Hi @dsargent, our aim is to simply integrate state data into the main CSV file. All indicators and indices will be the same. The policies reported will cover the overall policy environment for residents in that state (so for instance, it would include national border closures at C8).

There will be other more specific datasets published from state data, and these may have different schemas, but the main dataset will be the same.

**Comment by TobyPhillips** [comment]
If you haven't seen it yet, this data is now up!

**Comment by dsargent** [comment]
Thanks @TobyPhillips! Is this the correct file? `OxCGRT_US_states_temp.csv` You had mentioned that it would be merged into the existing CSV but a separate file is fine too.

**Comment by dsargent** [comment]
@TobyPhillips I saw the update to the README explaining the new file for US states info -- thank you! We've already started digesting it.

Hope you don't mind another question: I see some free-flow comments in the US state file about mask ordinances. They are currently in the `M1 Notes` column. Are there plans to make this a first-class NPI, and if so, any idea of the timeline?

**Comment by gregbert42** [comment]
![image](https://user-images.githubusercontent.com/16961761/89730176-b8b53e00-da3c-11ea-9941-a3149ebd18f4.png)

Not sure I expected california to have a lower or even equal stringency to arizona. need to dig in more.

**Comment by TobyPhillips** [comment]
@dsargent – adding an indicator for masks is something we would like to do at some point, but haven't actually started yet. Still, we are pre-emptively starting to record in M1 to make life easier for us in the future.

@gregbert42 – is that actually the stringency index, or one of the other indices? Looking at the data, the stringency index is 58 for Arizona vs 65 for California.

**Comment by gregbert42** [comment]
StringencyIndex does not have a value on the latest date (aug 5), so I was
using  StringencyLegacyIndexForDisplay

If I go back 1 day (aug 4), then California has a 'stringencyindex'
(65.74), but arizona does not.

i am using
https://github.com/OxCGRT/covid-policy-tracker/blob/master/data/OxCGRT_US_states_temp.csv
- let me know if i am using the wrong file.
