### ISSUE TITLE
Missing policyActions in several daily files

### ISSUE THREAD

**Issue by ljubisa-milenkovic** [OxCGRT/covid-policy-tracker#3]
Hello,

Thank You for setting up this repository and sharing.
After API update to V2 some of records are missing "policyActions" list.
Attached file is listing which countries are missing this list on which date.
[missingpolicyActions_sort.txt](https://github.com/OxCGRT/covid-policy-tracker/files/4558440/missingpolicyActions_sort.txt)

Thank You

**Comment by TobyPhillips** [comment]
Hi there, thanks for flagging this, we are looking into it.

In the mean time, [OxCGRT/covid-policy-tracker/data](https://github.com/OxCGRT/covid-policy-tracker/tree/master/data) should have correct up-to-date data in CSV format. But do let us know if you spot any problems there too.

Thanks,
Toby

**Comment by ljubisa-milenkovic** [comment]
Hello Toby,
Thank You for a fast response.
I have checked the CSV file manually for some of the missing values and can confirm that CSV file is OK. 
CSV file being OK is one of the reasons why I have raised this issue.
Please let me know if and when the daily entries are updated.

Regards
Ljuba

**Comment by ljubisa-milenkovic** [comment]
Toby,

Thank You!
The list is now present in all API calls.

Regards
Ljuba
