### ISSUE TITLE
File error data/OxCGRT_latest.csv

### ISSUE THREAD

**Issue by alksak** [OxCGRT/covid-policy-tracker#32]
Something is wrong with this file.
![image](https://user-images.githubusercontent.com/2636241/89780209-a5c46b80-db19-11ea-8261-f74a018641e0.png)

**Comment by saptahash** [comment]
Hi @alksak 

Thanks for pointing this out! 

We're looking into this, but for now you could use the data in the timeseries folder. It's in wide format and disaggregates the indices, but is essentially the same data.

**Comment by saptahash** [comment]
Hi @alksak 

This seems to be working fine now, thanks for raising the issue.

**Comment by alksak** [comment]
Maybe it was github glitch. Thank you.
