### ISSUE TITLE
Error with OxCGRT_latest.csv

### ISSUE THREAD

**Issue by Raminen** [OxCGRT/covid-policy-tracker#34]
Hi the latest version of this csv is displaying an error:

![image](https://user-images.githubusercontent.com/25932835/90021709-88bea280-dca9-11ea-99e9-54f168ced798.png)

**Comment by sumalibajaj** [comment]
This specific csv file is broken for me too- I see the same as above.

**Comment by saptahash** [comment]
Hi, 

Thanks for pointing this out! 

The link seems to be working fine now. Could you check if you're able to view the file correctly?

**Comment by sumalibajaj** [comment]
Works alright now. Thanks!
