### ISSUE TITLE
Error in OxCGRT_latest.csv

### ISSUE THREAD

**Issue by alihaddad-dynideas** [OxCGRT/covid-policy-tracker#35]
Hi 

There is an error in the latest version of data/OxCGRT_latest.csv:

![image](https://user-images.githubusercontent.com/49282693/90167264-7a37c000-dd69-11ea-94cf-ed4a2d3e10ea.png)

Thanks

**Comment by saptahash** [comment]
Hi, 

The link seems back up. Could you check if this is working for you now? Generally we've noticed this to be a recurring problem over the past week - we'll try and fix this soon.

**Comment by alihaddad-dynideas** [comment]
Yes it is working now. I noticed this is a recurring problem. I use the old version of the file when this happens. Thank you
