### ISSUE TITLE
Data removed

### ISSUE THREAD

**Issue by turnipInvasion** [OxCGRT/covid-policy-tracker#36]
The csv data that was here before has been replaced with some html markup

**Comment by etiennecelery** [comment]
https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv

Yes this file doesn't contain the data.

**Comment by turnipInvasion** [comment]
Wait, previously I downloaded a dataset that had, in addition to the various stringency indices, the factors that went into the stringencies. Will this no longer be provided?

**Comment by saptahash** [comment]
Hi all, 

Thanks for bringing this up!

The link seems to be fixed now, but generally this is a recurring problem we've noticed over the past week. We're not yet sure why the problem pops up every now and then. We'll look into this - for now it seems a retry after a while would work.

**Comment by alksak** [comment]
@saptahash Same problem again. I mention it just for log purposes.
