### ISSUE TITLE
OxCGRT_latest.csv is corrupted

### ISSUE THREAD

**Issue by anandsinha1991** [OxCGRT/covid-policy-tracker#39]
OxCGRT_latest.csv is corrupted

**Comment by dsargent** [comment]
It seems that occasionally, when the github action fires and accesses the web server, it gets an error from the web service from whence it's pulling the data. But it doesn't detect the error, and commits whatever it received, which in some cases is an HTML error page!

For example, see commit `918ae2b64f48c15d5520cf8f9aa1c64d3e2b2892`. Right side in this screenshot is the previous data file, which is the expected CSV data. On the left is the HTML page that was erroneously committed. The next commit fixed the problem. Perhaps add some error checking and retry if possible?

![Screenshot_2020-08-19_15-51-10](https://user-images.githubusercontent.com/934884/90697691-d3a16280-e233-11ea-9a4d-d7cb33f905ef.png)

**Comment by TobyPhillips** [comment]
We have implemented a few fixes over the last few days (both on our server and here on GitHub) to prevent this from happening, and it seems to have done the trick. But please re-open this issue ASAP if you see it again.
