### ISSUE TITLE
Where can we find information on the new policies?

### ISSUE THREAD

**Issue by chuckcerrillo** [OxCGRT/covid-policy-tracker#4]
I can't seem to find the working paper. Clicking on the link brings me to https://www.bsg.ox.ac.uk/research/publications/variation-government-responses-covid-19 and the only link there links back to https://www.bsg.ox.ac.uk/research/research-projects/coronavirus-government-response-tracker.

**Comment by TobyPhillips** [comment]
Hi, thanks for flagging this. There was a problem on our website.
Should be fixed now, and downloadable from that link. Let me know if you still have issues.
-Toby

**Comment by chuckcerrillo** [comment]
Thank you for the quick response. I can see the paper now! Thanks for all of your work, appreciate it.
