### ISSUE TITLE
Data chart incorrect, please correct

### ISSUE THREAD

**Issue by KriszLengyel** [OxCGRT/covid-policy-tracker#41]
Hi,
great fan of the data & chart, however it is incorrect for Mexico. According to the online data, Mexico´s stringency index was 82.4 in May, but the chart shows only 62.4 (one major horizontal line lower!, **20 points lower than the actual data.**
Please correct it, I was going to use this chart in a journal article but cannot as it is incorrect.

Thanks in advance for the correction!
K. Lengyel

**Comment by saptahash** [comment]
Hi, 

Thanks for this! Are you referring to the chart under [https://github.com/OxCGRT/covid-policy-tracker/blob/master/images/country_charts/Mexico.png](url)? 

If so, this chart seems to be correct since it plots Government Response Index rather than the Stringency Index (the GRI for Mexico is ~63 in May, and is now at ~58. The SI as you pointed out correctly, is ~82 in May and currently ~71). 

Thanks, 
Saptarshi.

**Comment by KriszLengyel** [comment]
Hi Saptarshi, 

 

Yes, I refer to that chart, I thought the download contains the GSI, so than I´m a bit lost what´s the difference between Government response Index and the Stringency Index?  I´ll try to check. So the GSI is not available from Github as the GRI? I wanted to use for a publication (citing of course the source).

 

Thanks again,

Krisztina

**Comment by saptahash** [comment]
Hi, 

The Stringency Index (SI) and the Government Response Index (GRI) are two different indices. They're both available in the published [data csv](https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv). 

There's more information on the differences between the two indices here - [https://github.com/OxCGRT/covid-policy-tracker#our-documentation-and-working-papers-have-more-information](url). 

Currently, we don't publish the chart for Stringency Index v/s Cases/Deaths on the Github repo, but you can set-up this chart with the same [dataset](https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv). 

Saptarshi.

**Comment by KriszLengyel** [comment]
Thanks for the quick response, I´ll check both!

Cheers from Mexico,

Krisztina

**Comment by saptahash** [comment]
Thanks, I'm closing the issue for now - but please reach out over email at coviddata@bsg.ox.ac.uk if there's still some confusion about this.
