### ISSUE TITLE
Error in OxCGRT_latest.csv - multiple data points at national level data for US & UK

### ISSUE THREAD

**Issue by soham-98** [OxCGRT/covid-policy-tracker#43]
Hi,
There seem to be multiple entries for both UK & USA at the national-level data (RegionCode = Null) for a single date with different values for the stringency/openness indices.

**Comment by jkatr** [comment]
Here is what I get for US:

> tail(covid.data.web[covid.data.web$CountryName %in% 'United States' & covid.data.web$RegionCode=='',c('Date','GovernmentResponseIndex', 'GovernmentResponseIndexForDisplay')],20)
          Date GovernmentResponseIndex GovernmentResponseIndexForDisplay
47956 20200912                      NA                                NA
48221 20200912                   42.31                             42.31
47957 20200913                      NA                                NA
48222 20200913                   42.31                             42.31
47958 20200914                      NA                                NA
48223 20200914                   42.31                             42.31
47959 20200915                      NA                             67.63
48224 20200915                   42.31                             42.31
47960 20200916                      NA                             67.63
48225 20200916                   42.31                             42.31
47961 20200917                      NA                             67.63
48226 20200917                   42.31                             42.31
47962 20200918                      NA                             67.63
48227 20200918                   42.31                             42.31
47963 20200919                      NA                             67.63
48228 20200919                   42.31                             42.31
47964 20200920                      NA                             67.63
48229 20200920                   42.31                             42.31
47965 20200921                      NA                             67.63
48230 20200921                      NA                             42.31

**Comment by saptahash** [comment]
Hi, 

Yes we noticed this too. This might take us a day to solve, but we'll update on the progress soon. Thanks for bringing this up!

**Comment by saptahash** [comment]
Hi all, 

This has been resolved. The latest data is in the same folder. Please let us know if you're able to process the file correctly.

**Comment by jkatr** [comment]
seems to work now (tested for the US). thanks!

**Comment by soham-98** [comment]
Thanks! The issue seems to be resolved.
