### ISSUE TITLE
Column name casing

### ISSUE THREAD

**Issue by sebastianvermaas** [OxCGRT/covid-policy-tracker#44]
Hi, I noticed that the last commit to [the latest data](https://github.com/OxCGRT/covid-policy-tracker/blob/master/data/OxCGRT_latest.csv) updated column names from UpperCase to lowercase. 

Was this planned or is this a mistake? Changing our workflow to be more flexible to this, but just wanted to point out as others may face issues.

**Comment by sebastianvermaas** [comment]
@saptahash @TobyPhillips

**Comment by saptahash** [comment]
Hi @sebastianvermaas  

I'm currently looking through the csv and noticed that while there's visually no difference in the column names, on an R import it does convert everything to a lower case, which wasn't happening before. (The Stata action seems stable still?)

This definitely wasn't an intended change. The csv sourced from out backend is temporarily corrupted, so we've replaced it with a back-up version of the csv. This version was exported through Stata, which is what might have caused the change. Once the source csv is back up, it should go back to the previous column name format. 

I'll keep this issue open until the source csv is sorted.

Thanks for bringing this up!

**Comment by saptahash** [comment]
Hi @sebastianvermaas 

This has been resolved. Could you let us know if you're able to process the file as before?

**Comment by sebastianvermaas** [comment]
All is good again!
