### ISSUE TITLE
Israel data missing/out of date?

### ISSUE THREAD

**Issue by dsargent** [OxCGRT/covid-policy-tracker#45]
Since 9/20, the NPIs for Isreal have not been updated in the data feed. This is important because Israel recently went into a second lockdown, but this is not reflected in the data.

**Comment by saptahash** [comment]
Hi @dsargent 

Yes we've noted this as well, the updates should be out by the end of this week. I'll keep this issue open until we've completed the round of updates.  

Thanks for pointing this out! 
Saptarshi.
