### ISSUE TITLE
Missing data in V2 of API

### ISSUE THREAD

**Issue by ljubisa-milenkovic** [OxCGRT/covid-policy-tracker#5]
Hello,
Did some format analyses of the data coming from the DATE/COUNTRY API and have some concerns.
There are many entries that are missing data:
* policy_value_display_field (one or several policies are missing this field, but others have in dome files)
*  stringencyData - stringencyData":{"msg":"Data unavailable"}. This causes response to miss important values like value_date and country_code and processing is much harder.

* Also in many the policy Action  parameter "is_general" is still on OLD key "isgeneral". I think that S99 policy is not converted(?)
DNK_2020-04-29:{"policyActions":[{"policy_type_code":"S99","policy_type_display":"No data.  Data may be inferred for last 7 days.","policyvalue":1,"isgeneral":true,"notes":null}],"stringencyData":{"date_value":"2020-04-29","country_code":"DNK","confirmed":8851,"deaths":434,"stringency_actual":null,"stringency":81.47}}

There are only the syntax errors in my opinion. I have not been able to check for the quality of values. First I need help in making data uniform in order to proceed.
---------------------------------------------------
Regarding the "RANGE" API. In general it misses "policyActions" which makes this API unusable if one want the policyActions as well.
---------------------------------------------------
The CSV file
Keys are different between API and CSV, which makes it incompatible. I do not know if this is intentional or not. 
--------------------------------------------------
Attaching list of countries and dates for which data is, in my opinion, missing or wrong in DATE/COUNTRY API

I also have a couple of  questions regarding data update interval
1. Today is 2nd of May. When is data for 2nd of May available trough DATE/COUNTRY API?
2. If "source" today (2nd of May) changes values for previous days (lets say for 30th of April) will this change be reflected in Your data for that country on 30th of April?
[MissingDataInDailyObservations.txt](https://github.com/OxCGRT/covid-policy-tracker/files/4567303/MissingDataInDailyObservations.txt)
[isgeneral_OnOldFormat.txt](https://github.com/OxCGRT/covid-policy-tracker/files/4567304/isgeneral_OnOldFormat.txt)

Thanks for helping out!
Regards
Ljuba

**Comment by TobyPhillips** [comment]
Hi Ljuba, thanks for flagging this. We're looking into it and will hopefully fix these issues in the next few days.
-Toby

**Comment by TobyPhillips** [comment]
Hi Ljuba,

I think the issue about missing stringencyData should be fixed now, but let me know if not.

We're also looking at the legacy is_general field (it should not be there in v2 of the API). But this might take a little while longer for us to work through.

Thanks,
Toby

**Comment by ljubisa-milenkovic** [comment]
Thank You Toby!
Have checked missing stringencyData and it seems that most of them are no populated. The once till missing are:
 2020-01-27 PNG
2020-01-27 POL
2020-01-27 PRI
2020-02-26 COD
2020-02-26 COL
2020-04-13 HND
2020-04-14 HND
2020-04-15 HND
2020-04-16 HND
2020-04-16 MUS
2020-04-16 QAT
2020-04-17 GRL
2020-04-17 HND
2020-04-17 MUS
2020-04-17 PRT
2020-04-17 QAT
2020-05-04 ESP

HOWEVER!!!!!! Grate work in bringing 7K+ to 7+ :-)

A HINT!
"isgeneral" is connected to OLD policy S99 beeing present:
{"policyActions":[{"policy_type_code":"S99","policy_type_display":"No data.  Data may be inferred for last 7 days.","policyvalue":1,"isgeneral":true,"notes":null}]

Regards
Ljuba
