### ISSUE TITLE
Possible additional measures

### ISSUE THREAD

**Issue by jc-bm** [OxCGRT/covid-policy-tracker#8]
Thanks for putting this together. I read that you welcome feedback and will consider additional measures. Advice on:

-self isolation e.g. stay at home for x days if you have a fever 
-social distancing e.g. keep two meters from people not in your household 

would be nice to have. I couldn't see a proxy, I imagine both would be lumped with public info campaigns, but apologies in case I missed something.

**Comment by TobyPhillips** [comment]
Yeah, I think you are correct. Both would broadly come under public information campaigns.

The first would also probably be captured as C6=1 (recommend not to leave house) if the government is recommending that people with symptoms stay at home. But C6 is really meant to describe policies that affect the whole population.

Thanks for the suggestions; I will add these to our list of potential additions.
