### ISSUE TITLE
No reported data for North Macedonia

### ISSUE THREAD

**Issue by vbresan** [OxCGRT/covid-policy-tracker#80]
There is no reported data for North Macedonia at all. Is it a glitch or something else?

**Comment by saptahash** [comment]
Hi! Thanks for pointing this out. We're trying to figure out what might have led to this - I'll update once this is sorted!

**Comment by saptahash** [comment]
Hi @vbresan, 

An update on this - we aren't recording MKD policies yet. We do have it in our pipeline of new countries to record data for, so we might see this come up in the next few months. I'll update this thread once we release MKD data. If you'd like to discuss this further (we're happy to!), could you please email us at coviddata@bsg.ox.ac.uk? 

Thanks!
