### ISSUE TITLE
Uruguay H7 Vaccination Policy update

### ISSUE THREAD

**Issue by 3dgiordano** [OxCGRT/covid-policy-tracker#81]
Uruguay currently has vaccination availability for the entire population over 18 years.

Source: https://www.gub.uy/uruguaysevacuna

I provide information on how the stages were executed

3/1/21 - Essential personnel: Police, firefighters, military, education workers and INAU, active and all of them under 60 years of age

3/8/21 - 50 to 70 years old: From 55 to 59 years old, then the band was extended to 50 to 70 years in five border cities and finally it was extended to people of this age throughout the country

3/12/21 - Vulnerable: Persons deprived of liberty and the staff of detention facilities (having started with women's facilities and INISA).

3/16/21 - Vulnerable: Home vaccination of people who live and work in residential areas (ELEPEM).

3/15/21 - Health Personnel: Prioritized Health Personnel (CTI and related services, swabs-vaccinators, intra and extra hospital door and emergency services and hemodialysis centers).

3/22/21 - Health personnel: All health personnel in the healthcare area (dentists, psychologists, physiotherapists and clinics of various specialties). After this stage, the administrative health personnel will be vaccinated.

3/22/21 - Vulnerable: Continuation of home vaccination of people who live and work in residential areas (ELEPEM).

3/22/21 - Over 80 years old: Vaccination for people over 80 years old self valid

3/29/21 - 18 to 70 years: General public between 18 to 70 years

4/10/21 - 71 to 79 years old: General public incorporating the remaining group from 71 to 79 years old.

Source: https://www.gub.uy/ministerio-salud-publica/comunicacion/noticias/comunicado-sobre-plan-vacunacion-contra-covid-19

It will probably be necessary to update the score of H7_Vaccination Policy.

Regards.
David

**Comment by saptahash** [comment]
Hi David, 

Thanks a lot for this, these notes are very helpful. We've passed this onto our review team and we should have the URY data reveiwed in this cycle. I'll update on this thread once we've reviewed the data.

**Comment by 3dgiordano** [comment]
Hi @saptahash 

I noticed that as of this change made on April 12, the data for Uruguay were updated to a more adequate evaluation.

https://github.com/OxCGRT/covid-policy-tracker/commit/8140aed9ab1cbdf3aeb47d36f990560815512ea6#diff-be17aa51588ed55cd71b3d4b753d28ae29a38690b6b5a36821934f22f663ab1bR177

Thanks to you and everyone on the team.
