### ISSUE TITLE
National data for USA not updating since 3/30?

### ISSUE THREAD

**Issue by willjobs** [OxCGRT/covid-policy-tracker#83]
Hi, I just noticed that the national data for the USA doesn't seem to be updating anymore, but the region/state-level data is. Is there a reason for that? See attached screenshots, one showing data for Alaska (with data updated through 4/6) and one showing data for the national dataset for the US (with data updated through 3/29).

![USA_alaska](https://user-images.githubusercontent.com/7775919/114408833-d14f9800-9b77-11eb-9729-b0f2258e0354.png)
![USA_national](https://user-images.githubusercontent.com/7775919/114408834-d14f9800-9b77-11eb-9bfb-362271d261f3.png)

**Comment by saptahash** [comment]
Hi @willjobs, 

Thanks for raising the issue. We're a bit behind on our USA national data updates. It'll likely be updated this round, so perhaps you should be able to see the data by the weekend. Apologies for this.

**Comment by willjobs** [comment]
No problem! I wanted to let you know in case there was a sneaky bug that creeped into your data extract process. Thanks for following up!

**Comment by willjobs** [comment]
Just following up on this-- it looks like it's gotten updated, so I'll close this issue. The most recent national data (as of 5 minutes ago) for the U.S. goes through April 12. Thank you again for your help!
