### ISSUE TITLE
Index values missing lately

### ISSUE THREAD

**Issue by ksokolovic** [OxCGRT/covid-policy-tracker#85]
We noticed that `StringencyIndex`, `GovernmentResponseIndex`, `ContainmentHealthIndex` and `EconomicSupportIndex` values are missing from the `OxCGRT_latest.csv` file lately. In particular, for some countries, these indexes were available until a couple of days ago. Now they are all `nan` values.

**Comment by vbresan** [comment]
Today all countries are missing it except the US. :-/

**Comment by saptahash** [comment]
Hi, apologies for the delay in attending to this. We've just fixed it, could you confirm that you're able to view the indices correctly?

**Comment by vbresan** [comment]
Looks fine! Could this happen in future as well or was it just a glitch?

**Comment by whyalwaysrose** [comment]
Working again, thanks!

**Comment by saptahash** [comment]
We're looking into what caused the issue. This hasn't happened before -- it's likely a glitch but we'll try and find out exactly what might have gone wrong.

Thanks everyone for pointing this out promptly! I'll close the issue.
