### ISSUE TITLE
Loss of stringency index field for several countries

### ISSUE THREAD

**Issue by nhartland** [OxCGRT/covid-policy-tracker#87]
Hi there,

First of all, many thanks for producing and maintaining this repo!

I've noticed recently that the stringency index is no longer set in the data for many countries. For example as of right now France is not returning values for the stringency index for the whole data history, either through the API or through the CSV file available in this repository.

This problem appears to have been occurring intermittently for a few days, each time the full history becoming unset.

**Comment by nhartland** [comment]
The commit https://github.com/OxCGRT/covid-policy-tracker/commit/ba26d0b78510b514f33f14f747497ea97c6e07a9 seems to have restored the values.

Is this intermittent outage to be expected?

**Comment by tboby** [comment]
@nhartland The root cause of this intermittent error was resolved yesterday, so this shouldn't occur again.
Sorry about that!

**Comment by nhartland** [comment]
Perfect, thanks for the quick reaction!
